### ISSUE TITLE
Profile references a query temp_id that does not exist

### ISSUE THREAD

**Issue by nikicat** [jazzband/django-silk#103]
Silk raised an error after sending concurrent requests to `runserver`. [Sentry error report](https://app.getsentry.com/share/issue/36303837382e313134333531343537/)

**Comment by avelis** [comment]
```shell
SilkInternalInconsistency: Profile references a query temp_id that does not exist. This should never happen, please file a bug report
  File "django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "silk/middleware.py", line 127, in process_response
    self._process_response(response)
  File "silk/middleware.py", line 114, in _process_response
    collector.finalise()
  File "silk/collector.py", line 165, in finalise
    raise SilkInternalInconsistency('Profile references a query temp_id that does not exist. '
```

**Comment by avelis** [comment]
@nikicat What setup are you running to locally test out concurrent requests. I have been looking for a way to simulate this via a unit test rig but haven't found much.

**Comment by nikicat** [comment]
This issue occurred inside local `./manage.py runserver` while I was doing some actions that imply ajax requests in multiple tabs of my browser. I don't known any reliable way to reproduce this issue. If I found one I will surely post here.
