### ISSUE TITLE
Filters are in milliseconds but indicates seconds

### ISSUE THREAD

**Issue by dvinegla** [jazzband/django-silk#115]
> Request
> Took longer than  **seconds  seconds**, executed more than  n
> queries, and spent longer than **seconds  seconds** executing queries.

**Comment by ka28kumar** [comment]
Hello @avelis @SebCorbin ,
I'm new to OSS and would love to contribute to this.
From what I can gather I need to change the text `seconds` to `milliseconds` in `profile.html` and `requests.html`. Does that work?

**Comment by avelis** [comment]
@ka28kumar yes I believe that is all that needs to change to meet the acceptance criteria of this ticket.
