### ISSUE TITLE
Action done in the DB shown on the queries list in the view

### ISSUE THREAD

**Issue by javaguirre** [jazzband/django-silk#132]
It would be nice to have the action made (`DELETE`, `UPDATE`,`SELECT` ...) in the queries list (on `/silk/profile/(\d+)/sql/` and `/silk/request/(uuid)/sql/`. For example:

Now:

<img width="929" alt="screen shot 2016-07-25 at 13 18 33" src="https://cloud.githubusercontent.com/assets/488556/17099818/f81b49d0-526a-11e6-977e-0fd24209c09d.png">

After:

<img width="929" alt="screen shot 2016-07-25 at 13 18 33" src="https://cloud.githubusercontent.com/assets/488556/17099851/420c3c48-526b-11e6-8628-84be79ab4cf3.png">

What do you think?

**Comment by avelis** [comment]
@javaguirre This is another good enhancement suggestion.

**Comment by javaguirre** [comment]
I'll try to spend some time working on this feature.

**Comment by albertyw** [comment]
Should be fixed in #611
