### ISSUE TITLE
Queries made with objects.raw() are not logged, query EXPLAIN

### ISSUE THREAD

**Issue by netcitylife** [jazzband/django-silk#154]
Why are queries made with Model.objects.raw() not logged?
Also it would be very useful to execute explain for each logged query (when enabled via new config option) to see the more or less precize query execution plan.

**Comment by avelis** [comment]
@soulhunter1987 Without investigating to much into it. It could be the case that RawQuerySet's are not being caught by the DataCollector utility class. I don't have much else to add until I further investigate into it.

**Comment by avelis** [comment]
@soulhunter1987 Looking at the other Github issues, we can see discussion on this issue here #80 .
