### ISSUE TITLE
DATA_UPLOAD_MAX_MEMORY_SIZE error

### ISSUE THREAD

**Issue by italomaia** [jazzband/django-silk#162]
I'm getting a RequestDataTooBig in my file uploads because of silk. 

silk/model_factory.py in body line 106

**Comment by avelis** [comment]
@italomaia Can you give us some more information into your setup and steps to how you are seeing this issue? A possible scrubbed stacktrace perhaps?

**Comment by amykyta** [comment]
I am seeing this too. It's an issue from Django's `Request.body` https://github.com/django/django/blob/master/django/http/request.py#L252. There is a check of `Content-Length` header against `settings.DATA_UPLOAD_MAX_MEMORY_SIZE`. In Django 1.10+ `DATA_UPLOAD_MAX_MEMORY_SIZE` defaults to 2.5 MB. The easiest solution is to just increase that limit provided resources are available. It may be a bug that using Silk exposes by calling `Request.body` before multipart form data can be parsed https://github.com/django/django/blob/master/django/http/request.py#L242.

**Comment by thenewguy** [comment]
I am encountering this as well

**Comment by thenewguy** [comment]
I've confirmed silk is the issue by adding the url to `SILKY_IGNORE_PATHS`.  The issue goes away.  A simple way to reproduce is to upload a large file to an admin view.  In my case a 3MB file triggers the issue but it depends on the project settings.

**Comment by swarnakumar** [comment]
Exact same issue. The error goes away when I remove silk, or when I do what @thenewguy mentions.

**Comment by chidg** [comment]
I found a workaround for this by checking request content type in my `silky_intercept` function and bypassing Silk if the content type is `multipart/form-data`.

It does involve using the `_` prefixed `_parse_content_type` function from silk, but you could easily replicate the logic in that if you don't want to depend on a private api.

```
multipart_content_type = "multipart/form-data"

def silky_intercept(request):
    from silk.model_factory import _parse_content_type

    content_type, char_set = _parse_content_type(request.META.get("CONTENT_TYPE", ""))
    return content_type != multipart_content_type

SILKY_INTERCEPT_FUNC = silky_intercept
```
You can adapt this to use with any other logic you already have in your `silky_intercept`.
