### ISSUE TITLE
DataError: value too long for type character varying(190)

### ISSUE THREAD

**Issue by tripliks** [jazzband/django-silk#179]
Hello,

I'm getting this exception for long urls ie. /resource/<jwt_token>. Looks like the limit is 190 chars.
Is there a way to have long urls logged?

**Comment by avelis** [comment]
@tripliks Sorry for the delay. The short answer is no and not for the foreseeable future.

URL fields are indexed values in the library. However, to be MySQL `ut8mb4` compliant the indexed column can't support values longer than 190 characters. You can see more details on the conversation about this issue here: https://github.com/django-silk/silk/issues/38 

Ultimately, v1.0.0 went forward with 190 char limit.

**Comment by avelis** [comment]
@tripliks You could tail strip out values longer than 190 via a `pre_save` signal I believe. Not the best solution but a workaround of sorts.

**Comment by avelis** [comment]
@tripliks Unless there is more of an issue to address I am looking at closing this issue.

**Comment by marcoaurelioneto** [comment]
We had been the same problem with it:

![image](https://user-images.githubusercontent.com/557439/27798369-5fe99db6-5fe7-11e7-9825-26281df43ba4.png)

**Comment by gdelnegro** [comment]
To expand on @marcoaurelioneto report, we are using Django v1.11.2, django-silk v1.0.0, PostgreSQL 9.4.12 and psycopg2 v2.7.1

**Comment by avelis** [comment]
@marcoaurelioneto You could tail strip out values longer than 190 via a pre_save signal I believe. Not the best solution but a workaround of sorts.

**Comment by avelis** [comment]
@gdelnegro The 190 character limit is an intended limit due to MySQL support. The best I can suggest is to tail strip out url values over the 190 character limit via a pre_save signal.

**Comment by pmontu** [comment]
I face the same issue with a different long url having a few uuid4s.

**Comment by smaccona** [comment]
Silk should make a sane path that fits in the 190 character limit to avoid breaking users' applications. I will open a PR.

**Comment by marcoaurelioneto** [comment]
In our case we were able to solve the problem by requesting the POST method.

**Comment by smaccona** [comment]
@avelis please can you review PR #313 when you get a chance? Thanks!
