### ISSUE TITLE
Limiting request/response data don't available in pypi version 

### ISSUE THREAD

**Issue by dobrovolsky** [jazzband/django-silk#218]
`garbage_collect` method doesn't exist in version from [pypi](https://pypi.python.org/pypi/django-silk).

**Comment by avelis** [comment]
@dobrovolsky Looks like we need to get a release out soon. Ugh.

**Comment by albertyw** [comment]
Depends on #187

**Comment by albertyw** [comment]
(I added in that logic).  I've gotten around it by pip installing directly from github.  My line in requirements.txt: 
```
-e git://github.com/jazzband/silk.git@09cf2c6a03cea2e6bc49a8a235f515b9ee30c4ab#egg=django-silk
```
