### ISSUE TITLE
Cannot execute silk_profile as silk is not installed correctly.

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [jazzband/django-silk#224]
Using 

- Django 1.11.6
- django-silk 1.0.0

I have installed `django-silk` and added to both middleware at the top as well as the installed apps.
I am not having an issue getting to the standard request pages as they all work wonderfully. However when attempting to instrument any function, I start getting the error below. One line of that error per `with silk_profile(name='blah'):` in the code. 

In my environment I have exported `export ENABLE_PROFILING='True'`
In my settings file I have the following:

```
# Determine profiling setting
SILKY_PYTHON_PROFILER = os.environ.get('ENABLE_PROFILING', 'False') == 'True'
SILKY_PYTHON_PROFILER_BINARY = SILKY_PYTHON_PROFILER
SILKY_PYTHON_PROFILER_RESULT_PATH = '/profiled/'
SILKY_META = SILKY_PYTHON_PROFILER
```

I have attempted to load silk as the first dependency assuming that the hooks for profile need to be loaded before the stack. Adding an import call at the start of the `apps.py` file doesn't seem to help any as I still get these errors.

When I enable profiling, I no longer get any metrics from the requests as well as getting the warnings listed below.

```
Performing system checks...

System check identified no issues (0 silenced).
WARNING:silk.profiling.profiler:Cannot execute silk_profile as silk is not installed correctly.
WARNING:silk.profiling.profiler:Cannot execute silk_profile as silk is not installed correctly
```

Thoughts, suggestions, ways you would rather see this issue formatted?

![selection_088](https://user-images.githubusercontent.com/53378/32861097-90f29db4-ca08-11e7-94f9-29aafc233d4a.png)

![selection_087](https://user-images.githubusercontent.com/53378/32861101-951f4a72-ca08-11e7-9682-0b0712747c20.png)

**Comment by hohenstaufen** [comment]
Can confirm this behaviour (although i do not get any warning message). 
Using Django 2.0.1 and django-silk 1.1.0

**Comment by garyayo** [comment]
Experiencing the exact same issue
django-silk=3.0
django=1.11.10

**Comment by bisibuka** [comment]
For me, the issue was using old-style MIDDLEWARE_CLASSES in my django settings, while django-silks checks in MIDDLEWARE variable

This may help https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-MIDDLEWARE_CLASSES

**Comment by pradeeproy28** [comment]
I am also experiencing the same issue, any resolution on django-silk=3.0
I have MIDDLEWARE_CLASSES in the settings.py as the application is developed on the eariler version of Django.
