### ISSUE TITLE
'gbk' codec can't decode byte 0xa7 in position 2608: illegal multibyte sequence

### ISSUE THREAD

**Issue by robinhli** [jazzband/django-silk#236]
When I install silk and enable it in my Django project, I saw this when I see a profiling.
the request page and sql page is ok.

**Comment by chen2013** [comment]
![2018-04-04_150117](https://user-images.githubusercontent.com/3285467/38293164-185a5584-3819-11e8-9604-7002b6303573.png)

**Comment by wangxinglong007** [comment]
![image](https://user-images.githubusercontent.com/15373068/180345259-f392ff5e-a99c-4236-a835-ba008c1f1f38.png)

**Comment by SebCorbin** [comment]
This is mostly due to your own code files not being encoded in UTF-8. Anyway this exception should be caught and a proper error message shown.

**Comment by SebCorbin** [comment]
This should have been fixed by @0650fab8
