### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by albertyw** [jazzband/django-silk#259]
I think it would be nice to make a small release to get all the recent commits out, particularly 5ba085368b13a79f92db1b874ecf5d4ad083450e

**Comment by avelis** [comment]
@albertyw I think that is a good idea. I have a draft started.

**Comment by albertyw** [comment]
Looking through the git log, I think the next release needs to be 2.0.0 because of dropped support for django 1.5, 1.6, and 1.7.
