### ISSUE TITLE
Make a new release of django-silk

### ISSUE THREAD

**Issue by albertyw** [jazzband/django-silk#282]
There have been several bugfixes (notably #275 and #278) and that should be released.  Hopefully this will also resolve #277

**Comment by albertyw** [comment]
@avelis did you

**Comment by avelis** [comment]
@albertyw I did. Would you like me to hold off or approve it? It was 1am central so I needed some sleep.

**Comment by albertyw** [comment]
I think it's good to go.

**Comment by avelis** [comment]
@albertyw Release was made to django-silk
