### ISSUE TITLE
Disabling Silk for specific URLs

### ISSUE THREAD

**Issue by physicalattraction** [jazzband/django-silk#292]
I have an API endpoint on which I can upload a photo using a multipart request. When Silk is trying to parse the request, I get a decoding error.

I now want to disable Silk for certain URL endpoints. Is this already possible? If so, how should I configure this? If not, would that be a good feature?

**Comment by MateuszBelczowski** [comment]
@physicalattraction Hi, I think that this [section of the README](https://github.com/jazzband/django-silk#custom-logic-for-recording-requests) could be helpful. You can create your custom intercept function and exclude unwanted URLs, e.g. 
```SILKY_INTERCEPT_FUNC = lambda request: 'foo' not in request.path```

**Comment by physicalattraction** [comment]
@MateuszBelczowski : I misinterpreted that part of the README, but I will check it out. Thanks for pointing this out!

**Comment by physicalattraction** [comment]
Works like a charm, thanks for pointing this out! :-D
