### ISSUE TITLE
MIddleware documentation is outdated

### ISSUE THREAD

**Issue by yozlet** [jazzband/django-silk#302]
Both the [`README`](../blob/master/README.md) and [the troubleshooting page](docs/troubleshooting.rst) contain this outdated advice:

> **Note:** The middleware placement is sensitive. If the middleware before `silk.middleware.SilkyMiddleware` returns from `process_request` then `SilkyMiddleware` will never get the chance to execute. Therefore you must ensure that any middleware placed before never returns anything from `process_request`. See the [django docs](https://docs.djangoproject.com/en/dev/topics/http/middleware/#process-request) for more information on this.

That "django docs" link hasn't gone to the right point in the Django middleware page since Django 1.9, which - as far as I can tell - is the last version that had `process_request()`. I eventually worked this out after having been scared by this note into trying to work out what it meant before placing the middleware.

I'd do a PR with improved advice, but I'm new enough to Silk that I don't know what it would be.

**Comment by avelis** [comment]
If you have time for a PR to improve the docs I can take a look and merge it in.
