### ISSUE TITLE
Silk while testing

### ISSUE THREAD

**Issue by ruckit-dev** [jazzband/django-silk#337]
I'd like to run some tests, and then be able to runserver and view the silk results.
Any guidance on achieving this?

I've made sure to install the silk app and middleware when testing, and I can see requests being logged, but the issue is that the test database gets reset/deleted after every run.

I tried a custom database router where all the 'silk' app stuff gets saved to a different database, but the test runner also deletes/resets that database.

My next approach is to get rid of my custom database router, and just have a custom test runner, where I make sure to not delete/reset the silk data in between runs.

But I'm just curious if anyone else has other ideas.

**Comment by jkeyes** [comment]
[pytest-django](https://pytest-django.readthedocs.io/en/latest/database.html#reuse-db-reuse-the-testing-database-between-test-runs) has a `--reuse-db` option.
