### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by xrmx** [jazzband/django-silk#339]
Hello, any chance you can cut a new release please?

**Comment by mbeacom** [comment]
https://github.com/jazzband/django-silk/releases/tag/3.0.2

**Comment by jezdez** [comment]
FYI, remember that this will need to be confirmed by @avelis before it's pushed to PyPI.

**Comment by xrmx** [comment]
Uhm looks like there's something broken. Tried installing the zip from github with

```
pip install https://github.com/jazzband/django-silk/archive/3.0.2.zip
```

or even instaling master with 

```
pip install git+https://github.com/jazzband/django-silk.git#egg=django-silk
```

and got 

```
  File "/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

This is with python 2.7 and django 1.11.

**Comment by xrmx** [comment]
oh it looks i am still using old MIDDLEWARE_CLASSES instead of MIDDLEWARE. Since it's deprecated not sure how this should be handled wrt to semver. A comment in the github release that MIDDLEWARE_CLASSES are not supported anymore may be helpful for others though. The documentation cite MIDDLEWARE since 2017 so it may be an issue only for the few people using it on old projects :)

**Comment by mbeacom** [comment]
@xrmx `MIDDLEWARE_CLASSES` is a deprecation that should be handled when upgrading to Django >= 1.10.
I am not sure if it's necessary to add a note about the `MIDDLEWARE_CLASSES` adjustment, but if the need is there...  Could we instead add a note to the last relevant Django < 1.10 release?

**Comment by xrmx** [comment]
@mbeacom MIDDLEWARE_CLASSES works perfectly fine in django 1.11, it has been removed in 2.0.

**Comment by mbeacom** [comment]
@xrmx Right, but it was officially deprecated in 1.10, ultimately removed from backwards compatibility in 2.0.
