### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by chidg** [jazzband/django-silk#354]
Hi, 
is it possible to have a new version released on PyPI?
There have been some recent merges that would be useful to us but are not in 3.0.2 (eg https://github.com/jazzband/django-silk/pull/342)

thank you

**Comment by avelis** [comment]
@nasirhjafri I tried publishing the 3.0.3 release and it failed to upload do the following error below.

```
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by nasirhjafri** [comment]
@avelis Pushed the fix, Can you please try publishing again? Thanks.

**Comment by avelis** [comment]
@nasirhjafri Someone needs to resend the release artifacts to jazzband so then I can see the new links to publish the new tarball and wheel. I would do but I really don't have the time at the moment.

**Comment by hiimdoublej** [comment]
Hey guys would love to have that new version 3.0.3 available

**Comment by nasirhjafri** [comment]
@avelis I'm getting this error while pushing to jazzband. 
```
twine upload --repository jazzbandsilk dist/*  
Uploading distributions to https://jazzband.co/projects/silk/upload
Uploading django_silk-3.0.3-py2.py3-none-any.whl
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.73M/1.73M [00:04<00:00, 444kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 404 Client Error: NOT FOUND for url: https://jazzband.co/projects/silk/upload
```

Any ideas?

**Comment by avelis** [comment]
@nasirhjafri 
`NOTE: Try --verbose to see response content.`

Not sure if there is any response content.

**Comment by hiimdoublej** [comment]
Dear developers, any update on this ? Thanks

**Comment by nasirhjafri** [comment]
@avelis Can you please confirm the PyPI release request?

**Comment by avelis** [comment]
@nasirhjafri I would say abandon `3.0.3` and try again with `3.0.4`
