### ISSUE TITLE
CORS: Can I make it work with CORS Middleware?

### ISSUE THREAD

**Issue by EverWinter23** [jazzband/django-silk#364]
From `django-silk`:
> Therefore you must ensure that any middleware placed before never returns anything from process_request

From `django-cors-headers`:
> CorsMiddleware should be placed as high as possible, especially before any middleware that can generate responses such as Django's CommonMiddleware or Whitenoise's WhiteNoiseMiddleware. If it is not before, it will not be able to add the CORS headers to these responses.

The Problem: Request is blocked if `CORS` headers aren't added first, which means the middleare needs to come first-- *Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at localhost-url.*

**Edit:** It does work with `cors_headers`, only problem is, if the query takes longer, i.e. 30-50s, I get `CORS` error, is there like an implicit `timeout` or something that has not been documented?

**Comment by kb0304** [comment]
+1
