### ISSUE TITLE
Ability to clean up all requests/queries. 

### ISSUE THREAD

**Issue by wlisesrivas** [jazzband/django-silk#365]
Sometime we want to start from clean requests/queries and we need to manually delete all the silk data from the database.

Could be helpful if you can delete all the entries by clicking a button in the UI.

**Comment by nasirhjafri** [comment]
Added in https://github.com/jazzband/django-silk/pulls

**Comment by nasirhjafri** [comment]
Added in release 4.0.0 (https://github.com/jazzband/django-silk/issues/384)
