### ISSUE TITLE
fix UnicodeDecodeError

### ISSUE THREAD

**Issue by w-xh** [jazzband/django-silk#367]
When I viewing "Details"，UnicodeDecodeError raised
![image](https://user-images.githubusercontent.com/47207969/66698038-30c3b200-ed0d-11e9-83e3-19d212819fb5.png)

Because  response body with Chinese (it works well with English response body.)
I modify the _code in https://github.com/jazzband/django-silk/blob/master/silk/views/code.py Then it can work
before:
![image](https://user-images.githubusercontent.com/47207969/66697479-96616f80-ed08-11e9-9b77-b7de61f47a20.png)
after:
![image](https://user-images.githubusercontent.com/47207969/66697484-a416f500-ed08-11e9-855e-f77860d4acc8.png)

**Comment by SebCorbin** [comment]
Fixed by #490
