### ISSUE TITLE
Headers are not sanitized

### ISSUE THREAD

**Issue by StefanMich** [jazzband/django-silk#375]
I am using silk in a project with a tastypie api, and when using apikey or basic auth these are sent as request header 'Authorization'. These headers are stored in silk which is security risk.

**Comment by StefanMich** [comment]
Implemented it with a hardcoded list, to be consistent with how bodies are masked. 
It might be better to implement it as a setting so any header can be masked. I am happy to do that change if anyone finds that to be better

**Comment by nasirhjafri** [comment]
Added in release 4.0.0 (https://github.com/jazzband/django-silk/issues/384)

**Comment by chidg** [comment]
Great that you've done this @StefanMich and that @nasirhjafri has merged it, however is it possible to have it also merged into a maintained 3.x version? Silk 4.0 does not support Django <2.2, which means Django 1.11 which is currently still a supported LTS release doesn't have access to this important security fix.
