### ISSUE TITLE
Erro import six from django.utils

### ISSUE THREAD

**Issue by endersonmenezes** [jazzband/django-silk#377]
I searched for "Django 3.0" and "django 3.0" and found no doubt of the kind. I am creating a upgrade plan for my system for Django 3.0, and I came across the following error

`
from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/python3.8/site-packages/django/utils/__init__.py)
`

According to @adamchainz in https://github.com/adamchainz/django-cors-headers/issues/366 this function was removed.

**Comment by dangelsaurus** [comment]
oh no this isn't good

**Comment by adamchainz** [comment]
See the bottom of the django release notes: https://docs.djangoproject.com/en/3.0/releases/3.0/

**Comment by nasirhjafri** [comment]
Added in release 4.0.0 (https://github.com/jazzband/django-silk/issues/384)
