### ISSUE TITLE
Django 3 support 

### ISSUE THREAD

**Issue by pyprism** [jazzband/django-silk#382]
Does this package support django 3.0  ?  Recently I upgraded my project from django 2.x to 3.0.
When I tried to run manage.py command it throws this error : 

```
 File "/../.env/lib/python3.7/site-packages/silk/models.py", line 21, in <module>
    from silk.config import SilkyConfig
  File "/../.env/lib/python3.7/site-packages/silk/config.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/../.env/lib/python3.7/site-packages/django/utils/__init__.py)
```

**Comment by knyghty** [comment]
This is being addressed in https://github.com/jazzband/django-silk/pull/380

**Comment by nasirhjafri** [comment]
Added in https://github.com/jazzband/django-silk/pull/385 and https://github.com/jazzband/django-silk/pull/380

**Comment by nasirhjafri** [comment]
Added in release 4.0.0 (https://github.com/jazzband/django-silk/issues/384)
