### ISSUE TITLE
Prepare Release 4.0

### ISSUE THREAD

**Issue by nasirhjafri** [jazzband/django-silk#384]
Since this is a major release as we are dropping python 2 support, we will move to 4.x instead of 3.x.

- [x] Check the support with Django 3.0
- [x] Test django silk if its working fine. 
- [x] Prepare a change log

**Comment by auvipy** [comment]
should be django 2.2+ only

**Comment by nasirhjafri** [comment]
Yep, There were issues with Django 3.0 reported https://github.com/jazzband/django-silk/issues/382. I'll need to verify it. Also, I'll do a PR to drop django<2.2 support.

**Comment by iMerica** [comment]
This as blocked me. Is anyone aware of a fork that supports 3?

**Comment by nasirhjafri** [comment]
@iMerica master branch is now supporting 3.0 
We'll be releasing today to PyPI

**Comment by iMerica** [comment]
Great news. I'm doing some tests now then. 

Ping me if I can help!

**Comment by withthelemons** [comment]
Any news on when will version 4.0 be released?

**Comment by nasirhjafri** [comment]
Upload to PyPI failed. Can you please check @mbeacom ?

**Comment by nasirhjafri** [comment]
@jezdez @avelis @albertyw @mbeacom @mtford90 Can we please do something regarding PyPI issue?
Also opened a ticket in jazzband-roadies help ->  https://github.com/jazzband-roadies/help/issues/179

Thanks,

**Comment by jezdez** [comment]
I'll take a closer look tomorrow.

**Comment by jezdez** [comment]
So, it seems as if the 4.0 release was released to the Jazzband site as intended, and the project lead as listed on https://jazzband.co/projects/django-silk @avelis should have received an email asking to confirm the release.

@avelis Could please take a look at the 4.0 release and confirm it on https://jazzband.co/projects/django-silk so it's pushed to PyPI?

@nasirhjafri Please contact the project lead first the next time you have an issue with releasing, thanks!

**Comment by jezdez** [comment]
> Upload to PyPI failed. Can you please check @mbeacom @avelis ?

For the record, it did fail for unrelated reasons, basically the travis test matrix setup isn't ideal and doesn't use any conditions to deploy to the Jazzband site. Travis deploy failures were ignored in the past but now fail the build so it's more visible. I'll work on a patch to use tox-travis and simplofy the setup like other Jazzband projects.

Or actually, @aleksihakli do you want to apply your newly gained experience with tox-travis on this repo, too? :)

**Comment by nasirhjafri** [comment]
> @nasirhjafri Please contact the project lead first the next time you have an issue with releasing, thanks!

@jezdez I tagged @avelis 11 days ago but got no response. Thanks for looking into it.

**Comment by jezdez** [comment]
> > @nasirhjafri Please contact the project lead first the next time you have an issue with releasing, thanks!
> 
> @jezdez I tagged @avelis 11 days ago but got no response. Thanks for looking into it.

Yeah, I saw that and you did the sensible next step by reaching out to me. We'll figure out a way forward from here. If we're not seeing a response in the coming days, I'll step in as surrogate for @avelis and review the release.

**Comment by jezdez** [comment]
Please welcome @nasirhjafri as additional project lead to the project!

@nasirhjafri One thing I noticed is that the setup.py of 4.0 doesn't include a [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) parameter which would make sure that pip will only install 4.0 on Python 3. I would like to remove the already uploaded 4.0 files on the Jazzband package index and redo the 4.0 release to improve this important release. Would that be ok?

**Comment by jezdez** [comment]
To be clear, it would require adding the python_require parameter and then deleting and re-doing the Git tag as well with the latest commit. Whether we want to improve the Travis config before that is not super important I think since we know the Travis config deploy errors are really false positives.

**Comment by nasirhjafri** [comment]
@jezdez yes that would be okay, thanks!

**Comment by nasirhjafri** [comment]
@jezdez If we want to redo git release tag, https://github.com/jazzband/django-silk/pull/391 would also be in this release, lemme add it in release notes too.

**Comment by nasirhjafri** [comment]
> @nasirhjafri One thing I noticed is that the setup.py of 4.0 doesn't include a [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) parameter which would make sure that pip will only install 4.0 on Python 3. I would like to remove the already uploaded 4.0 files on the Jazzband package index and redo the 4.0 release to improve this important release. Would that be ok?

@jezdez I've updated the release notes, please feel free to redo it. Thanks

**Comment by jezdez** [comment]
@nasirhjafri I've deleted the previously uploaded 4.0 files on the Jazzband package index, but would like you to do the release again on Github. Just go to the releases page on https://github.com/jazzband/django-silk/releases and delete and recreate the 4.0 release. Make sure to copy the release notes before you do, so it's easier to recreate. Once you've created the release, the package files will be uploaded to the Jazzband package index again and you'll receive email notifications to confirm the release, just follow the instructions.

**Comment by nasirhjafri** [comment]
Version 4.0.0 is released to PyPI.

**Comment by aleksihakli** [comment]
>  Or actually, @aleksihakli do you want to apply your newly gained experience with tox-travis on this repo, too? :)

Sure @jezdez I'll clean up the CI setup.

**Comment by jezdez** [comment]
> > Or actually, @aleksihakli do you want to apply your newly gained experience with tox-travis on this repo, too? :)
> 
> Sure @jezdez I'll clean up the CI setup.

Thank you @aleksihakli!
