### ISSUE TITLE
Support functional cProfile enable

### ISSUE THREAD

**Issue by tredzko** [jazzband/django-silk#390]
Hey!

Been enjoying getting this running in our project and really enjoy the functionality we have.

One thing we were looking to have was the ability to turn the cProfiler on/off per request, similar to how we can turn the intercept on/off functionally using the request object. There's a number of times where we still care about getting response times and tracking them, but don't want to slow down the requests too heavily with the profiler.

**Comment by nasirhjafri** [comment]
Released in 4.0.0 https://github.com/jazzband/django-silk/issues/384
