### ISSUE TITLE
Data missing for requests with larger response times

### ISSUE THREAD

**Issue by valentijnscholten** [jazzband/django-silk#392]
Hi,

Github might not be the best place, but I couldn't find any (curreny) slack/chat/mailing list.

I have enabled silk on my django app and basically it seems to be working. Except for some requests no data is shown. These are typically the longer running requests. Anything under 10s for now seems to be reported OK.

![image](https://user-images.githubusercontent.com/4426050/72678754-0ec69200-3aa9-11ea-8fa1-f1347f12d173.png)

Is there some kind of limit / timeout somewhere? There is nothing in the logs.

Obviously these longer running requests are the first ones I would like to analyse/profile/optimize :-)

**Comment by liu1000** [comment]
I had the same issue and am sharing a workaround.

Although silk can't show the results in GUI, it did generate cProfile .prof files in your `MEDIA_ROOT`. Then I was able to see the results by
```
python -m pstats 04e396e2-d5b2-40e4-9d66-1c69d3385c9f.prof
```

In my `settings.py`:
```
SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True
```

**Comment by cmkishores** [comment]
Hi,  I am having the same issue. Did you get to solve this? @valentijnscholten

**Comment by SebCorbin** [comment]
The request is created at the beginning of analysis, and saved again with timings upon response being sent to the browser. Hence these kinds of request can happen for requests that are stopped/timeouted before finishing response, e.g.
 - requests debugged with pdb, and pdb is quit
 - request with extra long timeout (and Django is stopped in the meantime)

I'm not sure we can do anything about them, but at least you have an explanation :)
