### ISSUE TITLE
The "Clear DB" page doesn't work with PostgreSQL

### ISSUE THREAD

**Issue by Ikalou** [jazzband/django-silk#395]
The new "Clear DB" page makes use of `SET FOREIGN_KEY_CHECKS` to disable foreign key checks. This does not work with PostgreSQL and other databases. It fails with `ProgrammingError at /silk/cleardb/: unrecognized configuration parameter "foreign_key_checks"`.

I think we should either _a) duplicate all the logic_ inside of...

https://github.com/jazzband/django-silk/blob/d4b44030d82a669c4f497c6f4d52a2c185b36fce/silk/management/commands/silk_clear_request_log.py#L12

...into...

https://github.com/jazzband/django-silk/blob/b135b8ec09d48fc219c4f1b721e67eee5dbfa905/silk/views/clear_db.py#L12

...or b) _call the command inside of the view_.

If we can agree on the best method I can submit a pull request with a fix.

Thank you for taking a look at this!

**Comment by nasirhjafri** [comment]
I would prefer moving the logic to a common function and then call it in both view and command.

**Comment by nasirhjafri** [comment]
Added in 4.0.1
https://github.com/jazzband/django-silk/issues/407
