### ISSUE TITLE
Passing encoding parameter to json.loads was ignored and removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [jazzband/django-silk#402]
https://github.com/jazzband/django-silk/blob/639da91e61973268efe885ecc5524185748da762/project/tests/test_encoding.py#L81

Ref : https://bugs.python.org/issue39377

**Comment by nasirhjafri** [comment]
We've not added support for python 3.9 yet.

**Comment by tirkarthi** [comment]
I can add a PR for this.

**Comment by nasirhjafri** [comment]
sure, please create a PR.
