### ISSUE TITLE
django.db.utils.ProgrammingError: relation "silk_profile" does not exist

### ISSUE THREAD

**Issue by eshxcmhk** [jazzband/django-silk#416]
silk配置数据库连接路由到非```default```，在页面中```Clear DB```（只能勾选```All```）时，报错：
```django.db.utils.ProgrammingError: relation "silk_profile" does not exist```，根据Exception信息发现：
```
def delete_model(model):
    engine = settings.DATABASES['default']['ENGINE']
    table = model._meta.db_table
```
此处直接使用的```default```，难道不支持使用和业务、```django```不同的数据库吗？或者应该怎么配置呢？

**Comment by eshxcmhk** [comment]
```settings.DATABASES['default']```修改为```settings.DATABASES[model.objects.db]```可解决

**Comment by nasirhjafri** [comment]
@eshxcmhk Could you please update your comments in English? Thanks,

**Comment by nasirhjafri** [comment]
connects https://github.com/jazzband/django-silk/pull/417
