### ISSUE TITLE
Requests list should be one dimensional

### ISSUE THREAD

**Issue by Kern3l** [jazzband/django-silk#429]
Hey!

"Requests" view really begs to be a list, maybe even rows of a table (that can be sorted by just clicking on a header, or even it could be filtered by just clicking on a value of later rows). It would be easier to find what you want visually - moving your eyes in one dimension is quicker than in 2 as it is now.

Thanks in advance!

**Comment by mierz00** [comment]
I agree completely with @Kern3l. I'd love to have a list. 

Would you guys be willing to accept a pull request with this feature? 

I'm imagining a simple selector in the nav bar that allows you to choose a list or classic view. 

@nasirhjafri @albertyw

**Comment by nasirhjafri** [comment]
@mierz00 sure, please create a PR and tag me for review, thanks!

**Comment by auvipy** [comment]
thank you
