### ISSUE TITLE
Django Silk is not compatible with Django 3.1: EmptyResultSet is removed in Django 3.1

### ISSUE THREAD

**Issue by Tirzono** [jazzband/django-silk#431]
https://docs.djangoproject.com/en/3.1/releases/3.1/#id1

> * The compatibility imports of django.core.exceptions.EmptyResultSet in django.db.models.query, django.db.models.sql, and django.db.models.sql.datastructures are removed.

**Comment by quimey** [comment]
Are you planning a release with this fix?

**Comment by Tirzono** [comment]
I am working on a release PR now, at that point it will be up to @aleksihakli to merge it or not.

**Comment by aleksihakli** [comment]
@Tirzono I am not the project maintainer. You can find the maintainers at 

https://jazzband.co/projects/django-silk

Only @avelis and @nasirhjafri can release the sites through the Jazzband site to PyPI.

**Comment by nasirhjafri** [comment]
I've created a release, It will be published in a while. Thanks @Tirzono and @aleksihakli

**Comment by aleksihakli** [comment]
Great, thanks @nasirhjafri!

**Comment by nasirhjafri** [comment]
Published to PyPI.
