### ISSUE TITLE
ImportError EmptyResultSet

### ISSUE THREAD

**Issue by FrauElster** [jazzband/django-silk#434]
Hi guys,

I could not find this anywhere, so I always doubt myself, but i think there is actually an ImportError.
I am running django 3.1, freshly installed my venv today, so silk should be on the current version.

In `silk/sql.py` on line 4 I get a `ImportError: cannot import name 'EmptyResultSet' from 'django.db.models.sql'`. Thanks to PyCharms auto-complete greatness, I just removed the line, auto-imported it again so it now says `from django.core.exceptions import EmptyResultSet`. Now it runs properly.

Hopefully this was useful

**Comment by Tirzono** [comment]
Duplicate of #431 and fixed in #432
