### ISSUE TITLE
Silk shows 0 time for all queries?

### ISSUE THREAD

**Issue by ZhangYupengCHY** [jazzband/django-silk#442]
Using django 2.2.14 and django-silk 3.0. Just return overall time but the queries are all 0.Is some wrong about the version of django-silk or django?How can I solve the  bizarre issus. @avelis 

Package              Version
-------------------- ----------
asgiref              3.2.10
autopep8             1.5.4
certifi              2020.6.20
chardet              3.0.4
decorator            4.4.2
Django               2.2.14
django-silk          3.0.2
et-xmlfile           1.0.1
gprof2dot            2019.11.30
h5py                 2.10.0
idna                 2.10
jdcal                1.4.1
Jinja2               2.11.2
langdetect           1.0.8
MarkupSafe           1.1.1
mysqlclient          2.0.1
numpy                1.16.6
openpyxl             3.0.5
pandas               0.25.3
pip                  10.0.1
prettytable          0.7.2
py                   1.9.0
pycodestyle          2.6.0
pyecharts            1.8.1
PyExcelerate         0.9.0
Pygments             2.7.1
PyMySQL              0.10.0
python-dateutil      2.8.1
pytz                 2020.1
redis                3.5.3
requests             2.24.0
retry                0.9.2
setuptools           39.1.0
simplejson           3.17.2

![q1](https://user-images.githubusercontent.com/49268744/94506870-fc5c4500-0240-11eb-8902-a3274e4a846b.png)

**Comment by ZhangYupengCHY** [comment]
BTW.I check the database `silk_sqlquery`,empty,no record.And I am pretty sure I was queried anthoer table.
![q2](https://user-images.githubusercontent.com/49268744/94508907-9e7e2c00-0245-11eb-8a24-5597da082c62.jpg)

**Comment by gdalmau** [comment]
I experienced this issue with django 3.2; downgrading to `pip install "django<3.2"` worked for me until this issue is fixed.

**Comment by Jorl17** [comment]
@gdalmau Are you sure that you had the same exact issue? Did you see a "0" in for the queries, or did you simply not see any values there? 

When I tried Django 3.2, I stopped seeing values (not 0, just no value!), and indeed downgrading, at the time, worked. Notice how @ZhangYupengCHY is using Django 2.2.14!

**Comment by gevezex** [comment]
U have Django v3.1.0 and still have this issue.

**Comment by Jorl17** [comment]
Note that your issue is slightly different, because although you have a "0" in the queries, you have no value in the overall request time. These seem to be two different issues.

**Comment by gevezex** [comment]
Ok posted this in issue #442

**Comment by ZhangYupengCHY** [comment]
Its oky now.Thanks!

**Comment by dianaGera** [comment]
I had a similar problem with an endpoint that had a long loading time. 
Notised that `MySQL` aborted connection with `Error 1153 - Got a packet bigger than 'max_allowed_packet' bytes`

To fix it update the `my.cnf` in `/etc/mysql/`

    net_buffer_length=1000000 
    max_allowed_packet=1000000000

or run:

    set global net_buffer_length=1000000; 
    set global max_allowed_packet=1000000000;

**Comment by lennertcc** [comment]
> I had a similar problem with an endpoint that had a long loading time. Notised that `MySQL` aborted connection with `Error 1153 - Got a packet bigger than 'max_allowed_packet' bytes`
> 
> To fix it update the `my.cnf` in `/etc/mysql/`
> 
> ```
> net_buffer_length=1000000 
> max_allowed_packet=1000000000
> ```
> 
> or run:
> 
> ```
> set global net_buffer_length=1000000; 
> set global max_allowed_packet=1000000000;
> ```

This was my issue too.

For me this was enough:
`max_allowed_packet=1073741824`
