### ISSUE TITLE
django silk profile persmission clash with my profile permission.

### ISSUE THREAD

**Issue by infosrabah** [jazzband/django-silk#444]
Hi,

Can't make a  migrations, because I got 2 profile permissions, one of the profile silk and the other profile of my application,

since a lots of people have a profile model and use permissions, I really would like if django silk could change the name of their permission to not clash with other people profile permissions, like the name of django silk profile permission will be "profile_perm"... or something like that.

thank you.

**Comment by infosrabah** [comment]
I did change my profile name, but it wasn't ethic. to do so.

but it did fix the issue.

**Comment by SebCorbin** [comment]
Permission are not meant to clash, if they do, you should also check the `app_name` when querying permissions.
