### ISSUE TITLE
RemovedInDjango40Warning: `django.conf.urls.url` deprecated in favor of `django.urls.re_path`

### ISSUE THREAD

**Issue by jshields** [jazzband/django-silk#446]
Usage of deprecated function `url` results in a deprecation warning (`RemovedInDjango40Warning`):
https://github.com/jazzband/django-silk/blob/b3185b2670a32d866136a9ee96e8e16a7702bbfd/silk/urls.py#L1
```
/home/********/project/venv/lib/python3.6/site-packages/silk/urls.py:19: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    url(r'^requests/$', RequestsView.as_view(), name='requests'),
```

**Comment by MuslimBeibytuly** [comment]
@jshields it is already resolved and will be at 4.1.1 release
