### ISSUE TITLE
django.db.utils.ProgrammingError: relation "silk_request" does not exist 

### ISSUE THREAD

**Issue by Singh-Sg** [jazzband/django-silk#468]
django-silk 4.1.0    
Python 3.8.5
django-admin.py version 3.1.3

INSTALLED_APPS = [ 
...
'silk', 
...
']

MIDDLEWARE = [
...
'silk.middleware.SilkyMiddleware',
...
]

urlpatterns = [
...
url(r'silk/', include('silk.urls')),

...
]

python manage.py makemigrations silk
python manage.py migrate
python manage.py runserver 2000

all OK

When I go to http://127.0.0.1:2000/admin/
it raises below error > 

django.db.utils.ProgrammingError: relation "silk_request" does not exist
LINE 1: INSERT INTO "silk_request" ("id", "path", "query_params", "r...

**Comment by Singh-Sg** [comment]
We are good now.

**Comment by luisiacc** [comment]
> We are good now. Let me help you if you get the same issue.

@Singh-Sg what was your issue, how did you resolve it?

**Comment by chriswilley** [comment]
> > We are good now. Let me help you if you get the same issue.
> 
> @Singh-Sg what was your issue, how did you resolve it?

+1
