### ISSUE TITLE
How to profile request on Django Admin ? 

### ISSUE THREAD

**Issue by sorasful** [jazzband/django-silk#477]
Hello there ! 

I'm working with Django 3.2 and version django-silk==4.1.1.dev20+g76a9b1e   (install from a commit because they were troubles with queries not showing up, that's not relevant).

So I use Silk to profile my admin views, I get the time, the SQL queries made, but for getting the actual profiling it says in "Profiling" tab  "No Silk profiling was performed for this request. Use the silk_profile decorator/context manager to do so."

Where do you think we should put this decorator ? 

Thank you very much !

**Comment by pythonpro** [comment]
@Archmonger that ^ doesn't work.
>I'm not entirely sure why you want to profile the admin view, as it's mostly a debug tool.

Because admin pages can have custom code, that needs to be profiled. And, even standard admin features may significantly slow down the page, e.g. 'list_filter' in case of large table.

@sorasful Example for an admin list view page:
```python
class MyModelAdmin(admin.ModelAdmin):
    @silk_profile(name='Some name')
    def changelist_view(self, request, extra_context=None):
        return super().changelist_view(request, extra_context=extra_context)
```
