### ISSUE TITLE
[enhancement request] - Add an option to track what Python lines causes the most SQL queries

### ISSUE THREAD

**Issue by sorasful** [jazzband/django-silk#478]
Hello,

When using Django-Silk on a project, it is useful to know how many SQL queries are made, where they came from. For now we have a pretty clear understanding of this, we can sort by number of join, time consumed, the type of requests.

For now, we can take any query and see why it was called. 

But I wonder, wouldn't it be a good feature to be able to see, for a specific line, how many SQL queries are emitted ? Or maybe there's already something for this and I just didn't find it.

What do you think ?

Thanks.

**Comment by auvipy** [comment]
if you have implementation detail feel free to share

**Comment by SebCorbin** [comment]
I would say that displaying similar queries count (see #439) would be enough to identify which line are causing large number of queries in most cases.
