### ISSUE TITLE
.prof files are not cleared

### ISSUE THREAD

**Issue by vsmelov** [jazzband/django-silk#529]
I have 6gb of *.prof files in my static/media folder
how can i limit it?

SILKY_MAX_RECORDED_REQUESTS=10000

i clicked clear db in silky admin panel but i still see these files

**Comment by auvipy** [comment]
can you share more detail please?

**Comment by Archmonger** [comment]
@auvipy I've confirmed this occurs. Seems like the logic to delete DB rows does not delete files.

**Comment by eduzen** [comment]
@vsmelov I think you could use `python manage.py silk_clear_request_log` for clearing all logged data.

**Comment by eduzen** [comment]
So, as @Archmonger pointed out, it's the expected behavior of Django. So we can close this ticket, right @vsmelov?

**Comment by SebCorbin** [comment]
Agreed, this would be tackled by [django-unused-media](https://pypi.org/project/django-unused-media/) or [django-cleanup](https://pypi.org/project/django-cleanup/)
