### ISSUE TITLE
How to configure EXPLAIN format with silk?

### ISSUE THREAD

**Issue by iamkarlson** [jazzband/django-silk#530]
Currently, silk uses just EXPLAIN without any flags for profiling posrgres sql queries. Certain tools like https://app.pgmustard.com require JSON to be supplied so they can work the best. How would it be possible to use additional flags like ANALYZE, VERBOSE, BUFFERS, FORMAT JSON with current implementation of the silk profiler?

**Comment by Archmonger** [comment]
Implementing a custom `SILKY_PYTHON_PROFILER_FUNC = ...` would be the way to go for your scenario. 

You can also PR something like a `SILKY_EXPLAIN_FLAGS` variable as well.

**Comment by baruchoxman** [comment]
@iamkarlson @Archmonger I've implemented this functionality, any chance you could review and possibly approve my PR?

**Comment by baruchoxman** [comment]
@iamkarlson @albertyw Should we mark this one as "resolved" following my fix being merged?

**Comment by iamkarlson** [comment]
Sorry for leaving you out. We decided to stop using silk as it's heavily hurting our database usage. if we get back - I will certainly try it out! Thanks!
