### ISSUE TITLE
Hard to integrate with CSP rules in place

### ISSUE THREAD

**Issue by sgelis** [jazzband/django-silk#531]
`django-silk` makes extensive use of inline `<style>` and `<script>` tags in its templates. This makes it very hard to :

- Override default behavior of style and/or scripts (whole template needs to be overridden).
-Apply CSP rules properly on a project that wants to use Silk **and** proper CSP rules (almost all templates must be overridden to add `nonce` attributes all over the place).

Was there a historical reason to put all these `<style>` and `<script>` tags inline? Would a PR addressing this issue be considered OK for maintainers?

**Comment by Archmonger** [comment]
Not sure about the historical reasoning, but many django repositories use static files for CSS/JS. I see no reason why we can't do that here.

Feel free to PR this behavior.
