### ISSUE TITLE
RawPostDataException

### ISSUE THREAD

**Issue by luk156** [jazzband/django-silk#534]
i' m using DRF on POST requests i have an RawPostDataException

**Comment by luk156** [comment]
https://github.com/encode/django-rest-framework/issues/2774

**Comment by auvipy** [comment]
I am closing the issue as ambiguous

**Comment by luk156** [comment]
i'm using a custom parser

```
class MultipartJsonParser(parsers.MultiPartParser):

    def parse(self, stream, media_type=None, parser_context=None):
        result = super().parse(
            stream,
            media_type=media_type,
            parser_context=parser_context,
        )
        data = {}

        for key, value in result.data.items():
            if type(value) != str:
                data[key] = value
                continue
            if '{' in value or "[" in value:
                try:
                    data[key] = json.loads(value)
                except ValueError:
                    data[key] = value
            else:
                data[key] = value
        return parsers.DataAndFiles(data, result.files)
```

in a viewset:

```
class GestoreEventoViewSet(ModelViewSet):
    parser_classes = [MultipartJsonParser]
```

if a enable silk, post  requests don't work becouse raise RawPostDataException

**Comment by auvipy** [comment]
ok

**Comment by haplo** [comment]
My best guess is that silk is reading `request.body`, which makes other code that accesses the request body to fail with `RawPostDataException`.

https://github.com/jazzband/django-silk/blob/b6c3934ff606db0a208cd4c7f0461f6f7ea2787a/silk/model_factory.py#L245-L246

It would be useful to see the exception stacktrace.

**Comment by nicokant** [comment]
I'm having this issue too.
I managed to access body in another middleware without raising a RawPostDataException using this code:
```
body = str(response.renderer_context["request"].data)
```

**Comment by sumanshusamarora** [comment]
I have the same issue. Its not working well with DRF. My middlewares list is as below - 
```python
[
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "silk.middleware.SilkyMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "shared.middlewares.TimeZoneMiddleWare",
    "django_user_agents.middleware.UserAgentMiddleware",
]
```

**Comment by sanxchep** [comment]
> I'm having this issue too. I managed to access body in another middleware without raising a RawPostDataException using this code:
> 
> ```
> body = str(response.renderer_context["request"].data)
> ```

You are a god. 

This works,
Django - 4.x
Python - 3.8.x
Ubuntu - 20.04
