### ISSUE TITLE
No module named 'silkauthentication'

### ISSUE THREAD

**Issue by pollaro** [jazzband/django-silk#540]
I've used silk before on my code. I was re-installing it and updating my `settings.py`.

I followed the instructions in the documentation. Middleware was near the top, put silk in the Installed Apps section. 
Tried to run: 
`python manage.py syncdb`
`python manage.py makemigrations`
`python manage.py migrate`

All of them gave the same error:
```ModuleNotFoundError: No module named 'silkauthentication'```

**Comment by ulgens** [comment]
@pollaro Can you please share your `INSTALLED_APPS` list? It looks like there is a missing comma missing "silk" and "authentication" values.
