### ISSUE TITLE
Update to django 4

### ISSUE THREAD

**Issue by eduzen** [jazzband/django-silk#543]
Hey, I've been using the project for a while and I would like to contribute 😄 . I will try to open a new pull upgrading the django version to see if all tests are passing or not.

**Comment by Archmonger** [comment]
We've already released a version that is Django 3.x compatible.

Did you mean to say Django 4?

**Comment by eduzen** [comment]
yes, it was a mistake 😄

**Comment by eduzen** [comment]
Django 4 and 3 are already supported. My bad.
