### ISSUE TITLE
Pin dependencies

### ISSUE THREAD

**Issue by arghodayah** [jazzband/django-silk#548]
We are facing some dependencies issues while using django-silk because of [backtracking](https://pip.pypa.io/en/latest/topics/dependency-resolution/), it would be better to pin django-silk dependencies in requirements.txt?

**Comment by albertyw** [comment]
`requirements.txt` should only be needed when developing django-silk itself.  If you're only using django-silk as a dependency of a larger django project, requirements.txt isn't used and `pip` should only be reading the `install_requires` list in setup.py (https://github.com/jazzband/django-silk/blob/master/setup.py#L38-L47).  `install_requires` packages should generally not be pinned: https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

**Comment by albertyw** [comment]
Fixed in #556.
