### ISSUE TITLE
Release recent changes to PyPI

### ISSUE THREAD

**Issue by rolandcrosby-check** [jazzband/django-silk#551]
Hi, wanted to ping the project leads listed [on Jazzband](https://jazzband.co/projects/django-silk) (@albertyw @avelis @nasirhjafri) to see if anyone would be willing to cut a release of what's been merged to the master branch since 4.2.0 was released last October. My specific pain point is that the Silk release on PyPI breaks Django entirely in multi-database setups; #538 (which has been merged) fixes this, but without a proper PyPI release actually using the code is a suboptimal experience.

@albertyw judging by the other two leads' GitHub commit graphs they are unlikely to be available to cut a release; would you mind picking this up or delegating to @jezdez as described [here](https://jazzband.co/about/releases)?

**Comment by sztamas** [comment]
Hi,
:+1:  on this.

Currently pip installing from GitHub, because multi-database setups aren't working with the latest release.

Thanks!

**Comment by sztamas** [comment]
Thanks @albertyw !

**Comment by albertyw** [comment]
Django-silk v4.3.0 now available at https://pypi.org/project/django-silk/4.3.0/

**Comment by rolandcrosby-check** [comment]
Thanks so much!
