### ISSUE TITLE
Silk Profiler No Silk profiling was performed for this request. Use the silk_profile decorator/context manager to do so.

### ISSUE THREAD

**Issue by timurchikk** [jazzband/django-silk#624]
MIDDLEWARE = BASE_MIDDLEWARE + [
	"silk.middleware.SilkyMiddleware"
]

SILKY_PYTHON_PROFILER = True

I have a decorator silk_profile() on views, but i getting that issue

**Comment by SebCorbin** [comment]
Please provide the code where you use `@silk_profile()` or `with silk_profile():`

**Comment by timurchikk** [comment]
@silk_profile(name="View Get Basket")
    def get(self, request, format=None):
        basket = operations.get_basket(request)
        ser = self.serializer_class(basket, context={"request": request})
        return Response(ser.data)

**Comment by timurchikk** [comment]
version of django-silk==4.2.0
django==2..2.12

**Comment by SebCorbin** [comment]
Then I don't see why it would not work, could you check:
 - `MIDDLEWARE` _effectively_ contains `silk.middleware.SilkyMiddleware` at runtime
 - `SILKY_PYTHON_PROFILER` is _effectively_ set to true at runtime
 - `silk` is in INSTALLED_APPS
 - You're viewing the more recent request from the view being profiled

**Comment by timurchikk** [comment]
Thanks, problem was on installed apps, i changed "silk.apps.SilkConfig" to "silk"

**Comment by SebCorbin** [comment]
Closely related to https://github.com/jazzband/django-silk/issues/269
