### ISSUE TITLE
Insert queries are not being recorded

### ISSUE THREAD

**Issue by Aperyon** [jazzband/django-silk#630]
SELECTs, UPDATEs, DELETEs are recorded as expected, but INSERTs are not. I would expect INSERT queries to be recorded as well.

Minimal setup
``` bash
poetry init
poetry add django
poetry shell
django-admin startproject example
cd example
./manage.py createsuperuser
./manage.py runserver
```

Then add 
- `"silk"` to `INSTALLED_APPS`
- `"silk.middleware.SilkyMiddleware"` to `MIDDLEWARE`
- `urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]` in `urls.py`

Then log into django admin to
- create a user
- update the user
- delete the user

Then navigate to `/silk/` and see that
- queries in general are recorded
- `/admin/auth/user/add/` -> no INSERT query
- `/admin/auth/user/2/change/` -> yes UPDATE query
- `/admin/auth/user/2/delete/` -> yes DELETE query

**Comment by SebCorbin** [comment]
Closing in favor of https://github.com/jazzband/django-silk/issues/630
