### ISSUE TITLE
Package 'autopep8' shouldn't need to be required when installing django-silk

### ISSUE THREAD

**Issue by PabloAlexis611** [jazzband/django-silk#660]
Since `autopep8` is purely for Python code formatting, the installation of `autopep8` should be optional/maybe be provided via _extras_ instead. Maybe something like `pip install django-silk[dev]`

**Comment by albertyw** [comment]
django-silk supports generating a python snippet to refire a request - https://github.com/jazzband/django-silk/blob/ed3e3261af96dc054fe72b80cd567313f835515b/silk/code_generation/django_test_client.py#L44

This python snippet gets run through autopep8 so autopep8 is a runtime dependency of django-silk, not just a test dependency.
