### ISSUE TITLE
Middleware problem?? No request model was available when processing response. Did something go wrong in process_request/process_view?

### ISSUE THREAD

**Issue by KoKoKyaw** [jazzband/django-silk#68]
I would like to get your suggestions on the Silk.

I'm deploying the django-silk 0.5 into existing django (version 1.6.9) framework environment for checking web application performance.
So I added a null logger for silk in the settings.py of django framework. Before it I used to get No handlers could be found for logger "silk" error. After adding it, no more such error. But still not sure it is correct solutions. Plase suggest on this

I have two ways to launch my web app: using run server manage.py and using nginx (Our production is using uwsgi and nginx).
When I use the first method, I can successfully launch my web application.

But I am facing error "The requested URL The requested URL /..../.../accounts/login/ was not found on this server" when I use nginx which is supported to be used. 
I still cannot figure out the meaning of error in my uwsgi log "No request model was available when processing response. Did something go wrong in process_request/process_view?". 

Also Suspect the middleware is not supporting correctly.

Still cannot find out any solutions. 
Please suggest.

**Comment by mtford90** [comment]
Hey there - sorry you're having issues. Have you played around with the order of the middleware? If there is a piece of middleware that returns from `process_request` before Silk, it will not work as Silk will no longer have access to the `request` object which it needs to inspect

**Comment by KoKoKyaw** [comment]
yes I did play with the middleware order. Still getting error "No request model was available when processing response. Did something go wrong in process_request/process_view?". 

Your suggestions are appreciated.

thanks.

**Comment by mtford90** [comment]
The error "/..../.../accounts/login/ was not found on this server" - I can only assume that this is an issue with your nginx routing setup?

Does "No request model was available when processing response." occur within the same request as the nginx error?

**Comment by KoKoKyaw** [comment]
Thanks for your reply. 
Based on the wsgi err log, I took a look into the silk middleware.py. From there, I chased the function def and trace back. Knowing it is belonging to model_factory.py. I found out the path/routing issue (what I understand is nginx dont know the base path /base/path/ which is created by django framework). 
so try to exclude it by adding if condition as follows:
def construct_request_model(self):
         body, raw_body = self.body()
         query_params = self.query_params()
         path = self.request.path
         base_url = settings.BASE_URL
         #print 'base url', len(base_url)
         if path.startswith(base_url): #it will return an error if prefixed w/ /base/path/, so have to remove
               path = path[len(base_url)-1:]
         resolved = resolve(path)

Then I can run uwsgi and can launch my web app. :+1: 

regards,
KKK
