### ISSUE TITLE
Should we consider requirement `autopep8` only as development only?

### ISSUE THREAD

**Issue by sshishov** [jazzband/django-silk#718]
Currently installing `django-silk` will install `autopep8`, which will install other libraries...

In my opinion it is not required for the functionality and therefore should not be required on `production` like environment (which is our development machine). It is only required for development of this library or for PR creation, no?

In my opinion on end user machine only "required" for functionality libraries should be installed

**Comment by albertyw** [comment]
While in most libraries, `autopep8` is used only in the build/test steps, in django-silk, `autopep8` is used in the production environment https://github.com/albertyw/django-silk/blob/master/silk/code_generation/django_test_client.py which is used to generate test code to replay a request.  Therefore, `autopep8` must be installed as a dependency of django-silk.

**Comment by sshishov** [comment]
@albertyw thank you for explanation. Fair enough then to add it to the requirements :thumbsup:
