### ISSUE TITLE
Silk not working with django tenant schemas

### ISSUE THREAD

**Issue by sauravkhakurel** [jazzband/django-silk#724]
I am trying to add silk to a project having django tenant schemas. All configs are right and are done according to the silk documentation. After running the migrate_schemas command to run the migration on the tenant schemas, it executes successfully. 
![Screenshot from 2024-07-31 13-11-34](https://github.com/user-attachments/assets/022b966a-2990-4784-a663-045cc4dc6d2c)

I have included these in my local.py
INSTALLED_APPS += ("debug_toolbar", "django_extensions", "silk")  # noqa F405
MIDDLEWARE += (
    "silk.middleware.SilkyMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "apps.core.middlewares.QueryCountDebugMiddleware",
)  # noqa F405
DATABASE_ROUTERS = ("tenant_schemas.routers.TenantSyncRouter",)

But when I try to execute any request on the app I am getting the following error.
> django.db.utils.ProgrammingError: relation "silk_request" does not exist

Upon listing the tables in the tenant schema, the migrated silk tables are not shown but inside django_migrations the migrations for silk is there
![image](https://github.com/user-attachments/assets/c11b2b11-6df3-4e73-8022-3ccb75bdaeba)

Are there any workarounds for this issue? Thanks

**Comment by Tragio** [comment]
Hi @sauravkhakurel @gregapompe 👋 

Do you remember which migrations you reverted? I'm facing the same issue, already tried several things but not sure what I'm doing wrong 🤔 

Thank you 🙏

**Comment by gregapompe** [comment]
Sorry I don't :(
